feeds:
   -name: "Bloomberg Markets News"
   url: "https://feeds.bloomberg.com/markets/news.rss"

   -name: "Reuters Business News"
   url:    "http://feeds.reuters.com/reuters/businessNews"

   -name: "MarketWatch Top Stories"  
   url: "https://feeds.marketwatch.com/marketwatch/topstories/"

   -name: "Nasdaq Market News"
   url: "https://www.nasdaq.com/feed/rssoutbound?category=Markets"

   -name: "Federal Reserve Press Releases"
   url: "https://www.federalreserve.gov/feeds/press_all.xml"
